version: "3"

services:
  postgresql:
    container_name: postgresql
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apisolid

volumes:
  postgresql_data:
    driver: local
